- name: Add java repository
  apt_repository: repo='ppa:webupd8team/java' state=present

- name: Automatically select the Oracle License
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections

- name: Install Oracle Java 7
  apt: name=oracle-java7-installer update_cache=yes state=present
